import{auth,db,storage,collection,doc,getDoc,getDocs,addDoc,setDoc,query,where,limit,signOut,ref,uploadBytes,getDownloadURL,writeBatch,serverTimestamp}from './firebase.js';
const role=sessionStorage.getItem('rizvi_role'); if(!role) location.href='login.html';
const API=localStorage.getItem('RIZVI_API')||'';
const employee=JSON.parse(sessionStorage.getItem('rizvi_employee')||'null');
const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(id)?.classList.remove('hidden'); if(id==='alerts')loadAlerts();}
window.show=show;
async function list(name,n=500){const s=await getDocs(query(collection(db,name),limit(n)));return s.docs.map(d=>({id:d.id,...d.data()}));}
async function count(name){const s=await getDocs(query(collection(db,name),limit(10000)));return s.size;}
async function refresh(){try{const [employees,departments,designations,complaints,weekly]=await Promise.all([list('master_employee',10000),list('departments',500),list('designations',500),list('complaints',500),list('weekly_hours',5000)]);const active=employees.filter(e=>String(e.status||'ACTIVE').toUpperCase()==='ACTIVE').length;const red=weekly.filter(w=>String(w.status||'').toUpperCase()==='RED'||String(w.signal||'').toUpperCase()==='RED').length;const yellow=weekly.filter(w=>String(w.status||'').toUpperCase()==='YELLOW'||String(w.signal||'').toUpperCase()==='YELLOW').length; if($('cards'))$('cards').innerHTML=[['Employees',active],['Departments',departments.length],['Designations',designations.length],['Complaints',complaints.length],['Open',complaints.filter(x=>String(x.status||'').toUpperCase()==='PENDING'||String(x.status||'').toUpperCase()==='OPEN').length],['72h Red',red],['72h Yellow',yellow]].map(x=>`<div class="metric">${x[0]}<b class="${x[0].includes('Red')&&x[1]>0?'danger':x[0].includes('Yellow')&&x[1]>0?'warn':''}">${x[1]}</b></div>`).join('');if($('org'))$('org').innerHTML=`Departments: ${departments.length}<br>Sections: ${await count('sections')}<br>Floors/Locations: ${await count('floors')}<br>Designations: ${designations.length}<br>Categories: ${await count('categories')}`;if($('hours'))$('hours').innerHTML=`<span class="warn">${yellow}</span> at 72:00:00 &nbsp; <span class="danger">${red}</span> above 72:00:00`;if($('live'))$('live').textContent='LIVE • Firebase syncing every 10s'}catch(e){console.error(e);if($('cards'))$('cards').innerHTML='<div class="panel">Firebase unavailable or Firestore rules are not configured.</div>'}}
async function loadEmp(){let id=$('eid').value.trim();if(!id)return;try{let s=await getDocs(query(collection(db,'master_employee'),where('employeeId','==',id),limit(1)));if(s.empty)s=await getDocs(query(collection(db,'master_employee'),where('officialId','==',id),limit(1)));if(s.empty)throw Error('Employee not found');let e={id:s.docs[0].id,...s.docs[0].data()};let w=await getDocs(query(collection(db,'weekly_hours'),where('employee_id','==',id),limit(52)));let weekly=w.docs.map(x=>x.data());$('emp').innerHTML=`<div class="panel"><h2>${e.name||''} (${e.employeeId||e.officialId||id})</h2>Designation: ${e.designation||''}<br>Department: ${e.department||''}<br>Section: ${e.section||''}<br>Floor: ${e.floor||''}<br>Gross: ${e.gross_salary||0}</div><div class="panel"><h3>Weekly hours</h3>${weekly.map(x=>`<div>${x.week_start||''} — ${((x.total_seconds||0)/3600).toFixed(2)}h <b class="${x.status==='RED'?'danger':x.status==='YELLOW'?'warn':'ok'}">${x.status||''}</b></div>`).join('')}</div>`}catch(e){$('emp').innerHTML=`<div class="panel danger">${e.message}</div>`}}
window.loadEmp=loadEmp;
async function importEmp(){const f=$('empFile').files[0];if(!f)return;if(!confirm('Import employee master into Firebase? Existing IDs will be updated.'))return;try{const text=await f.text();const lines=text.split(/\r?\n/).filter(Boolean);const headers=lines.shift().split(',').map(x=>x.trim());let batch=writeBatch(db),n=0,b=0;for(const line of lines){const vals=line.split(/,(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)/).map(x=>x.replace(/^\"|\"$/g,'').trim());const r=Object.fromEntries(headers.map((h,i)=>[h,vals[i]||'']));const id=r.EMPLOYEE_ID||r.employee_id;if(!id)continue;batch.set(doc(db,'master_employee',id),{employeeId:id,officialId:id,name:r.NAME||'',designation:r.DESIGNATION||'',grade:r.GRADE||'',department:r.DEPARTMENT||'',section:r.SECTION||'',floor:r.FLOOR||'',line:r.LINE||'',category:r.CATEGORY||'',status:'ACTIVE',updatedAt:serverTimestamp()},{merge:true});n++;b++;if(b===450){await batch.commit();batch=writeBatch(db);b=0}}if(b)await batch.commit();$('importResult').textContent=JSON.stringify({rows_accepted:n,collection:'master_employee'},null,2);refresh()}catch(e){$('importResult').textContent=e.message}}
window.importEmp=importEmp;
async function capture(){let id=$('locEid').value.trim();if(!id)return alert('Employee ID required');navigator.geolocation.getCurrentPosition(async p=>{try{const r=await addDoc(collection(db,'location_pings'),{employee_id:id,latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,source:'GPS',captured_at:serverTimestamp()});$('loc').textContent=JSON.stringify({id:r.id,latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy},null,2)}catch(e){$('loc').textContent=e.message}},e=>$('loc').textContent=e.message,{enableHighAccuracy:true})}
window.capture=capture;
async function submitComplaint(form){try{const data=Object.fromEntries(new FormData(form).entries());await addDoc(collection(db,'complaints'),{employee_id:data.employee_id,type:data.typ,subject:data.subject,description:data.description||'',status:'SUBMITTED',created_at:serverTimestamp(),updated_at:serverTimestamp()});$('complaintMsg').textContent='Submitted successfully to Firebase.';form.reset()}catch(e){$('complaintMsg').textContent=e.message}}
$('complaintForm')?.addEventListener('submit',e=>{e.preventDefault();submitComplaint(e.target)});
async function loadAlerts(){if(!$('alertsList'))return;try{const [weekly,complaints,compliance,disciplinary]=await Promise.all([list('weekly_hours',5000),list('complaints',500),list('compliance_records',500),list('disciplinary_actions',500)]);const a=[];weekly.filter(w=>String(w.signal||w.status||'').toLowerCase()==='red').forEach(w=>a.push({cat:'Overtime',sev:'Critical',title:`${w.employee_name||w.employee_id||''} — OT Red Signal`,detail:`Over 72h OT for week ${w.week_start||''}`}));complaints.filter(c=>String(c.status||'').toLowerCase()==='pending').forEach(c=>a.push({cat:'Complaint',sev:'High',title:c.subject||'Pending complaint',detail:`Pending complaint from ${c.employee_name||c.employee_id||''}`}));compliance.filter(r=>String(r.status||'').toLowerCase()==='expired').forEach(r=>a.push({cat:'Compliance',sev:'High',title:`${r.document_type||'Document'} expired`,detail:`${r.employee_name||r.employee_id||''} — ${r.document_title||''}`}));disciplinary.filter(d=>String(d.status||'').toLowerCase()==='open').forEach(d=>a.push({cat:'Disciplinary',sev:d.severity||'Medium',title:`${d.action_type||'Action'} — ${d.employee_name||''}`,detail:d.description||'Open action'}));const rank={Critical:0,High:1,Medium:2,Low:3};a.sort((x,y)=>(rank[x.sev]??9)-(rank[y.sev]??9));$('alertsList').innerHTML=a.length?a.map(x=>`<div class="panel"><b>${x.title}</b><br><small>${x.detail}</small><span class="badge">${x.cat} • ${x.sev}</span></div>`).join(''):'<p>No active alerts. Everything looks good.</p>'}catch(e){$('alertsList').innerHTML='<p>Unable to load alerts. Check Firestore rules.</p>'}}
window.logout=async()=>{try{await signOut(auth)}catch{}sessionStorage.clear();location.href='login.html'};
refresh();setInterval(refresh,10000);

if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
