const API=localStorage.getItem("RIZVI_API")||"http://localhost:8000";
function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));document.getElementById(id).classList.remove("hidden")}
async function j(url,opt){let r=await fetch(API+url,opt);if(!r.ok)throw new Error(await r.text());return r.json()}
async function refresh(){try{let s=await j("/api/dashboard/summary");document.getElementById("cards").innerHTML=[["Employees",s.employees],["Departments",s.departments],["Designations",s.designations],["Complaints",s.complaints],["Open",s.open_complaints],["72h Red",s.red_72h],["72h Yellow",s.yellow_72h]].map(x=>`<div class="metric">${x[0]}<b class="${x[0].includes('Red')&&x[1]>0?'danger':x[0].includes('Yellow')&&x[1]>0?'warn':''}">${x[1]}</b></div>`).join("");let o=await j("/api/org");document.getElementById("org").innerHTML=`Departments: ${o.departments.length}<br>Sections: ${o.sections.length}<br>Floors/Locations: ${o.floors.length}<br>Designations: ${o.designations.length}<br>Categories: ${o.categories.length}`;document.getElementById("hours").innerHTML=`<span class="warn">${s.yellow_72h}</span> at 72:00:00 &nbsp; <span class="danger">${s.red_72h}</span> above 72:00:00`;}catch(e){document.getElementById("cards").innerHTML='<div class="panel">API offline. Start the FastAPI server.</div>'}}
async function loadEmp(){let id=document.getElementById("eid").value.trim();if(!id)return;try{let e=await j("/api/employees/"+encodeURIComponent(id));let w=await j("/api/employees/"+encodeURIComponent(id)+"/weekly");document.getElementById("emp").innerHTML=`<div class="panel"><h2>${e.name} (${e.employee_id})</h2>Designation: ${e.designation}<br>Department: ${e.department}<br>Section: ${e.section}<br>Floor: ${e.floor}<br>Gross: ${e.gross_salary||0}<br>OT: ${e.ot_amt||0}</div><div class="panel"><h3>Weekly hours</h3>${w.map(x=>`<div>${x.week_start} — ${x.total_seconds/3600}h <b class="${x.status==='RED'?'danger':x.status==='YELLOW'?'warn':'ok'}">${x.status}</b></div>`).join("")}</div>`}catch(e){document.getElementById("emp").innerHTML=`<div class="panel danger">${e}</div>`}}
async function importEmp(){let f=document.getElementById("empFile").files[0];if(!f)return;let fd=new FormData();fd.append("file",f);try{let r=await j("/api/import/employees",{method:"POST",body:fd});document.getElementById("importResult").textContent=JSON.stringify(r,null,2);refresh()}catch(e){document.getElementById("importResult").textContent=String(e)}}
async function capture(){let id=document.getElementById("locEid").value.trim();if(!id)return alert("Employee ID required");navigator.geolocation.getCurrentPosition(async p=>{let fd=new FormData();fd.append("employee_id",id);fd.append("latitude",p.coords.latitude);fd.append("longitude",p.coords.longitude);fd.append("accuracy",p.coords.accuracy);let r=await j("/api/location",{method:"POST",body:fd});document.getElementById("loc").textContent=JSON.stringify({...r,latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy},null,2)},e=>document.getElementById("loc").textContent=e.message,{enableHighAccuracy:true})}
document.getElementById("complaintForm").addEventListener("submit",async e=>{e.preventDefault();try{let r=await j("/api/complaints",{method:"POST",body:new FormData(e.target)});document.getElementById("complaintMsg").textContent="Submitted: "+JSON.stringify(r)}catch(x){document.getElementById("complaintMsg").textContent=String(x)}});
refresh();setInterval(refresh,10000);
