import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import axios from 'axios';
import 'leaflet/dist/leaflet.css';
import './style.css';

const API=import.meta.env.VITE_API||'http://localhost:8000/api';
const WS=(import.meta.env.VITE_WS||API.replace(/^http/,'ws').replace(/\/api$/,''));
const auth=t=>({headers:{Authorization:`Bearer ${t}`}});

function App(){
 const[token,setToken]=useState(localStorage.getItem('rizvi_token'));const[me,setMe]=useState(null);const[tab,setTab]=useState('dashboard');
 useEffect(()=>{if(token)axios.get(API+'/me',auth(token)).then(r=>setMe(r.data)).catch(()=>{localStorage.removeItem('rizvi_token');setToken(null)})},[token]);
 if(!token)return <Login onLogin={t=>{localStorage.setItem('rizvi_token',t);setToken(t)}}/>;
 const admin=me?.role!=='EMPLOYEE'; const logout=()=>{localStorage.removeItem('rizvi_token');setToken(null)};
 const tabs=['dashboard','performance','attendance','location','cases',...(admin?['management','live-map','imports']:[])];
 return <div className="app"><header><div><b>RIZVI 360°</b><small>Integrated Workforce Management</small></div><div className="user">{me?.name} <span className="role">{me?.role}</span><button onClick={logout}>Logout</button></div></header><div className="layout"><nav>{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x.replaceAll('_',' ')}</button>)}</nav><main>
 {tab==='dashboard'&&<Dashboard t={token} management={admin}/>} {tab==='performance'&&<Performance t={token}/>} {tab==='attendance'&&<Attendance t={token}/>} {tab==='location'&&<LocationTracker t={token} me={me}/>} {tab==='cases'&&<Cases t={token}/>} {tab==='management'&&<Management t={token}/>} {tab==='live-map'&&<LiveMap t={token}/>} {tab==='imports'&&<Imports t={token}/>} 
 </main></div></div>
}
function Login({onLogin}){const[u,setU]=useState('');const[p,setP]=useState('');const[e,setE]=useState('');async function go(x){x.preventDefault();try{const f=new URLSearchParams();f.set('username',u);f.set('password',p);const r=await axios.post(API+'/auth/login',f);onLogin(r.data.access_token)}catch(z){setE(z.response?.data?.detail||'Login failed')}}return <div className="login"><div className="login-card"><h1>RIZVI 360°</h1><p>Employee & Management Portal</p><form onSubmit={go}><input placeholder="Official ID / Card No" value={u} onChange={x=>setU(x.target.value)} required/><input type="password" placeholder="Password" value={p} onChange={x=>setP(x.target.value)} required/><button>Sign In</button></form>{e&&<div className="error">{e}</div>}</div></div>}
function Card({title,value,sub}){return <div className="card metric"><span>{title}</span><strong>{value??'—'}</strong><small>{sub}</small></div>}
function Dashboard({t,management}){const[d,setD]=useState(null);useEffect(()=>{axios.get(API+(management?'/dashboard/management':'/dashboard'),auth(t)).then(r=>setD(r.data))},[t,management]);if(!d)return <Loading/>;if(management)return <><h2>Management Dashboard</h2><div className="grid"><Card title="Active Employees" value={d.employees.active} sub={`of ${d.employees.total}`}/><Card title="Performance" value={`${d.performance.average}%`} sub={`${d.performance.red_count} red evaluations`}/><Card title="Open Cases" value={d.complaints.open} sub={`${d.complaints.total} total`}/><Card title="Production" value={`${d.production.achievement_pct}%`} sub={`${d.production.achievement} / ${d.production.target}`}/><Card title="Quality DHU" value={`${d.quality.dhu}%`} sub={`${d.quality.defects} defects`}/></div><div className="card"><h3>Live Location</h3><p>Open <b>Live Map</b> to view only employees/devices that have granted location permission and are actively sending coordinates.</p></div></>;return <><h2>My Dashboard</h2><div className="grid"><Card title="Punch Days" value={d.attendance.punch_days}/><Card title="Working Hours" value={d.attendance.hours}/><Card title="OT Hours" value={d.attendance.ot_hours}/><Card title="Performance" value={`${d.performance}%`}/><Card title="Cases" value={d.complaints}/><Card title="Training Records" value={d.trainings}/></div></>}
function Performance({t}){const[k,setK]=useState([]);const[e,setE]=useState({});const[msg,setMsg]=useState('');useEffect(()=>{axios.get(API+'/kpis',auth(t)).then(r=>setK(r.data))},[t]);async function save(kpi){const a=e[kpi.id]||'NO';if(a==='PARTIAL'&&!e[`n${kpi.id}`])return setMsg('Partial completion requires a note.');try{await axios.post(API+'/evaluations',{kpi_id:kpi.id,period:kpi.period,period_key:new Date().toISOString().slice(0,10),answer:a,score:a==='PARTIAL'?Number(e[`s${kpi.id}`]||0):undefined,note:e[`n${kpi.id}`]||null},auth(t));setMsg('Saved successfully')}catch(x){setMsg(x.response?.data?.detail||'Save failed')}}return <><h2>Daily KPI Evaluation</h2>{msg&&<div className="notice">{msg}</div>}<div className="card">{!k.length&&<p>No KPI template assigned.</p>}{k.map(x=><div className="kpi" key={x.id}><div><b>{x.title}</b><small>{x.description||'Weight '+x.weight}</small></div><select value={e[x.id]||'NO'} onChange={z=>setE({...e,[x.id]:z.target.value})}><option>YES</option><option>NO</option><option>PARTIAL</option></select>{e[x.id]==='PARTIAL'&&<input placeholder="Reason / note" value={e[`n${x.id}`]||''} onChange={z=>setE({...e,[`n${x.id}`]:z.target.value})}/>}<button onClick={()=>save(x)}>Save</button></div>)}</div></>}
function Attendance({t}){const[d,setD]=useState(null);useEffect(()=>axios.get(API+'/dashboard',auth(t)).then(r=>setD(r.data)),[t]);return <><h2>Attendance & OT</h2><div className="grid"><Card title="Duty Days" value={d?.attendance.punch_days}/><Card title="Total Hours" value={d?.attendance.hours}/><Card title="OT Hours" value={d?.attendance.ot_hours}/></div><div className="card"><h3>Working-hour policy</h3><p>The server calculates time from imported punch records. Weekly OT thresholds are configurable in the policy layer.</p></div></>}
function LocationTracker({t,me}){
 const[consent,setConsent]=useState(localStorage.getItem('rizvi_location_consent')==='yes');const[status,setStatus]=useState('Not started');const[coords,setCoords]=useState(null);const[accuracy,setAccuracy]=useState(null);const[ws,setWs]=useState(null);const watchRef=useRef(null);const wsRef=useRef(null);
 const stop=()=>{if(watchRef.current!==null)navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null;if(wsRef.current)wsRef.current.close();wsRef.current=null;setWs(null);setStatus('Stopped')};
 const start=()=>{if(!consent)return setStatus('Consent is required');if(!navigator.geolocation)return setStatus('This device/browser has no Geolocation API');
  const socket=new WebSocket(`${WS}/ws/location/employee?token=${encodeURIComponent(t)}`);wsRef.current=socket;setWs(socket);
  socket.onopen=()=>{setStatus('Connected — waiting for GPS');watchRef.current=navigator.geolocation.watchPosition(pos=>{const p={type:'location',latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy,consent:true};setCoords([p.latitude,p.longitude]);setAccuracy(p.accuracy);socket.send(JSON.stringify(p));setStatus('Live — last position sent '+new Date().toLocaleTimeString())},err=>setStatus('GPS error: '+err.message),{enableHighAccuracy:true,maximumAge:5000,timeout:15000})};
  socket.onerror=()=>setStatus('WebSocket connection error');socket.onclose=()=>{if(watchRef.current!==null)navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null;setStatus('Connection closed')};
 };
 useEffect(()=>()=>stop(),[]);
 return <><h2>My Live Location</h2><div className="card"><p><b>Employee:</b> {me?.employee_id} — {me?.name}</p><label className="consent"><input type="checkbox" checked={consent} onChange={e=>{setConsent(e.target.checked);localStorage.setItem('rizvi_location_consent',e.target.checked?'yes':'no');if(!e.target.checked)stop()}}/> I voluntarily authorize this device to share my current location with RIZVI 360 while tracking is active.</label><div className="actions"><button disabled={!consent||!!ws} onClick={start}>Start Live Tracking</button><button className="secondary" disabled={!ws} onClick={stop}>Stop</button></div><p className="status">{status}</p>{coords&&<div className="coords">Latitude: {coords[0].toFixed(6)} · Longitude: {coords[1].toFixed(6)} · Accuracy: {accuracy?Math.round(accuracy)+' m':'—'}</div>}<p className="muted">Tracking uses the device's permitted GPS/network location. A phone number alone is not used to obtain carrier-level location.</p></div></>}
function LiveMap({t}){const mapRef=useRef(null);const mapObj=useRef(null);const markers=useRef(new Map());const[status,setStatus]=useState('Connecting…');useEffect(()=>{if(!mapRef.current||mapObj.current)return;const map=L.map(mapRef.current).setView([23.8103,90.4125],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);mapObj.current=map;const socket=new WebSocket(`${WS}/ws/location/admin?token=${encodeURIComponent(t)}`);socket.onopen=()=>setStatus('Live connection established');socket.onmessage=e=>{const d=JSON.parse(e.data);if(d.type!=='location_update')return;const latlng=[d.latitude,d.longitude];let m=markers.current.get(d.employee_id);const text=`<b>${d.name||d.employee_id}</b><br/>ID: ${d.employee_id}<br/>${d.department||''} ${d.section||''}<br/>Accuracy: ${d.accuracy?Math.round(d.accuracy)+' m':'—'}<br/>${new Date(d.captured_at).toLocaleString()}`;if(!m){m=L.marker(latlng).addTo(map).bindPopup(text);markers.current.set(d.employee_id,m)}else{m.setLatLng(latlng).setPopupContent(text)}};socket.onerror=()=>setStatus('Live connection error');socket.onclose=()=>setStatus('Live connection closed');return()=>{socket.close();map.remove();mapObj.current=null}},[t]);return <><div className="map-head"><h2>Live Employee Location</h2><span className="live-dot">● {status}</span></div><div className="card"><p className="muted">Only employees/devices that explicitly grant location permission and send GPS/network coordinates appear here. This is not carrier/GSM subscriber tracking.</p><div ref={mapRef} className="map"/></div></>}
function Cases({t}){const[s,setS]=useState({kind:'COMPLAINT',subject:'',body:''});const[list,setList]=useState([]);const[msg,setMsg]=useState('');const load=()=>axios.get(API+'/complaints/mine',auth(t)).then(r=>setList(r.data));useEffect(load,[t]);async function send(x){x.preventDefault();const f=new FormData();Object.entries(s).forEach(([k,v])=>f.append(k,v));try{await axios.post(API+'/complaints',f,{headers:{Authorization:`Bearer ${t}`}});setMsg('Submitted');setS({kind:'COMPLAINT',subject:'',body:''});load()}catch(z){setMsg(z.response?.data?.detail||'Failed')}}return <><h2>Employee Voice</h2><form className="card form" onSubmit={send}><select value={s.kind} onChange={x=>setS({...s,kind:x.target.value})}><option>COMPLAINT</option><option>SUGGESTION</option><option>APPLICATION</option></select><input placeholder="Subject" value={s.subject} onChange={x=>setS({...s,subject:x.target.value})} required/><textarea placeholder="Details" value={s.body} onChange={x=>setS({...s,body:x.target.value})} required/><button>Submit</button>{msg&&<small>{msg}</small>}</form><div className="card"><h3>My Cases</h3>{list.map(x=><div className="case" key={x.id}><b>#{x.id} {x.subject}</b><span>{x.status}</span><p>{x.response||'Awaiting management response.'}</p></div>)}</div></>}
function Management({t}){const[d,setD]=useState(null);useEffect(()=>axios.get(API+'/dashboard/management',auth(t)).then(r=>setD(r.data)),[t]);return <><h2>Director / GM Control</h2>{d&&<div className="grid"><Card title="Employees" value={d.employees.active}/><Card title="Red Performance" value={d.performance.red_count}/><Card title="Open Complaints" value={d.complaints.open}/><Card title="Production %" value={`${d.production.achievement_pct}%`}/><Card title="DHU %" value={`${d.quality.dhu}%`}/></div>}<div className="card"><h3>Location Governance</h3><p>Live Map access is restricted to authorized management roles. Location records are timestamped and retained in the database for audit.</p></div></>}
function Imports({t}){const[type,setType]=useState('employees');const[msg,setMsg]=useState('');const endpoints={employees:'/admin/import/employees',punches:'/admin/import/punches',salary:'/admin/import/salary',training:'/admin/import/training',production:'/admin/import/production'};async function up(x){const f=x.target.files[0];if(!f)return;const fd=new FormData();fd.append('file',f);try{const r=await axios.post(API+endpoints[type],fd,{headers:{Authorization:`Bearer ${t}`,'Content-Type':'multipart/form-data'}});setMsg(JSON.stringify(r.data))}catch(z){setMsg(z.response?.data?.detail||'Import failed')}}return <><h2>Data Import Center</h2><div className="card form"><select value={type} onChange={x=>setType(x.target.value)}>{Object.keys(endpoints).map(x=><option key={x}>{x}</option>)}</select><input type="file" accept=".csv,.xlsx,.xls" onChange={up}/><div className="notice">{msg||'Import CSV/XLSX and the system will synchronize the corresponding module.'}</div></div></>}
function Loading(){return <div className="card">Loading…</div>}
createRoot(document.getElementById('root')).render(<App/>);
